### ISSUE TITLE
Add support for .jinja file extension

### ISSUE THREAD

**Issue by andrewtmendoza** [Lucas-C/pre-commit-hooks-java#4]
Would you consider adding the .jinja file extension to this hook?
https://jinja.palletsprojects.com/en/2.11.x/templates/#template-file-extension

**Comment by Lucas-C** [comment]
Good idea !
Done: https://github.com/Lucas-C/pre-commit-hooks-java/commit/8242d597053e97bce678cf2cb6b20942b4d9a493

**Comment by Lucas-C** [comment]
Released in `1.3.10`

**Comment by andrewtmendoza** [comment]
Thanks!
